[build]
  command = "npm run build"
  publish = ".next"
  environment = { NEXT_PRIVATE_TARGET = "server" }

[functions]
  directory = ".netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
